Repository YahoProject/Yaho_Backend, pull requests merged in 2024-08, with the labels that each got.

#23 [Feature] 일기쓰기 API
  src/main/java/com/example/yaho/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/yaho/apiPayload/exception/handler/GameIdHandler.java
  src/main/java/com/example/yaho/converter/DiaryConverter.java
  src/main/java/com/example/yaho/domain/Diary.java
  src/main/java/com/example/yaho/repository/DiaryRepository.java
  src/main/java/com/example/yaho/repository/GameRepository.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandService.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/com/example/yaho/web/controller/DiaryController.java
  src/main/java/com/example/yaho/web/dto/DiaryRequestDTO.java
  src/main/java/com/example/yaho/web/dto/DiaryResponseDTO.java
Labels: :sparkles: feature

#25 issue #18 ✨ [Feature/3] 카카오 로그인 API
  build.gradle
  src/main/java/com/example/yaho/config/WebConfig.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/repository/MemberRepository.java
  src/main/java/com/example/yaho/service/KakaoService/KakaoService.java
  src/main/java/com/example/yaho/web/controller/KakaoLoginController.java
  src/main/java/com/example/yaho/web/dto/KakaoAccountDto.java
  src/main/java/com/example/yaho/web/dto/KakaoTokenDto.java
  src/main/java/com/example/yaho/web/dto/LoginResponseDto.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#27 ✨ [Feature] 야구 승률 API 구현
  src/main/java/com/example/yaho/domain/Record.java
  src/main/java/com/example/yaho/repository/RecordRepository.java
  src/main/java/com/example/yaho/service/RecordService/RecordService.java
  src/main/java/com/example/yaho/web/controller/RecordController.java
Labels: :sparkles: feature

#30 ✨ [Feature] 야구 일기 조회
  src/main/java/com/example/yaho/config/SwaggerConfig.java
  src/main/java/com/example/yaho/converter/DiaryConverter.java
  src/main/java/com/example/yaho/domain/Diary.java
  src/main/java/com/example/yaho/repository/DiaryRepository.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryService.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/com/example/yaho/web/controller/DiaryController.java
  src/main/java/com/example/yaho/web/dto/DiaryRequestDTO.java
  src/main/java/com/example/yaho/web/dto/DiaryResponseDTO.java
Labels: :sparkles: feature

#34 ✨ [Feature] member 조회
  build.gradle
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/repository/MemberRepository.java
  src/main/java/com/example/yaho/service/MemberService/MemberService.java
  src/main/java/com/example/yaho/utils/SecurityUtil.java
  src/main/java/com/example/yaho/web/controller/MemberController.java
  src/main/java/com/example/yaho/web/dto/MemberResponseDTO.java
Labels: :sparkles: feature

#38 ✨ [Feature] MVP 사진 업로드 API
  build.gradle
  src/main/java/com/example/yaho/aws/s3/AmazonS3Manager.java
  src/main/java/com/example/yaho/config/AmazonConfig.java
  src/main/java/com/example/yaho/domain/Diary.java
  src/main/java/com/example/yaho/domain/Uuid.java
  src/main/java/com/example/yaho/repository/UuidRepository.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/com/example/yaho/web/controller/DiaryController.java
  src/main/java/com/example/yaho/web/dto/DiaryRequestDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#40 member 조회
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/domain/enums/FavoriteTeam.java
  src/main/java/com/example/yaho/service/KakaoService/KakaoService.java
Labels: :sparkles: feature

#41 ✨ [Feature] member 업데이트
  build.gradle
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/domain/enums/FavoriteTeam.java
  src/main/java/com/example/yaho/repository/MemberRepository.java
  src/main/java/com/example/yaho/service/KakaoService/KakaoService.java
  src/main/java/com/example/yaho/service/MemberService/MemberService.java
  src/main/java/com/example/yaho/utils/SecurityUtil.java
  src/main/java/com/example/yaho/web/controller/MemberController.java
  src/main/java/com/example/yaho/web/dto/MemberResponseDTO.java
Labels: :sparkles: feature

#44 ✨ [Feature] 일기 수정하기
  src/main/java/com/example/yaho/config/SecurityConfig.java
  src/main/java/com/example/yaho/converter/DiaryConverter.java
  src/main/java/com/example/yaho/domain/Diary.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/repository/DiaryRepository.java
  src/main/java/com/example/yaho/repository/GameRepository.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandService.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryService.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/com/example/yaho/web/controller/DiaryController.java
  src/main/java/com/example/yaho/web/dto/DiaryRequestDTO.java
  src/main/java/com/example/yaho/web/dto/DiaryResponseDTO.java
Labels: :sparkles: feature, :recycle: refactor

#47 ✨ [Feature] 마이페이지 관련 api
  build.gradle
  src/main/java/com/example/yaho/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/yaho/apiPayload/exception/handler/MemberHandler.java
  src/main/java/com/example/yaho/aws/s3/AmazonS3Manager.java
  src/main/java/com/example/yaho/config/AmazonConfig.java
  src/main/java/com/example/yaho/config/SecurityConfig.java
  src/main/java/com/example/yaho/converter/MemberConverter.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/domain/enums/FavoriteTeam.java
  src/main/java/com/example/yaho/repository/DiaryRepository.java
  src/main/java/com/example/yaho/repository/MemberRepository.java
  src/main/java/com/example/yaho/service/MemberService/MemberService.java
  src/main/java/com/example/yaho/utils/SecurityUtil.java
  src/main/java/com/example/yaho/web/controller/MemberController.java
  src/main/java/com/example/yaho/web/dto/MemberResponseDTO.java
  src/main/java/com/example/yaho/web/dto/MemberUpdateDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#45 ✨ [Feature] 일기 수정하기
  src/main/java/com/example/yaho/converter/DiaryConverter.java
  src/main/java/com/example/yaho/domain/Diary.java
  src/main/java/com/example/yaho/domain/Game.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/domain/enums/Location.java
  src/main/java/com/example/yaho/repository/DiaryRepository.java
  src/main/java/com/example/yaho/repository/GameRepository.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandService.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryService.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/com/example/yaho/web/controller/DiaryController.java
  src/main/java/com/example/yaho/web/dto/DiaryRequestDTO.java
  src/main/java/com/example/yaho/web/dto/DiaryResponseDTO.java
  src/main/java/com/example/yaho/web/dto/ScheduleResponseDTO.java
Labels: :sparkles: feature, :recycle: refactor

#48 ✨ [Feature] 마이페이지 관련 API
  build.gradle
  src/main/java/com/example/yaho/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/yaho/apiPayload/exception/handler/MemberHandler.java
  src/main/java/com/example/yaho/aws/s3/AmazonS3Manager.java
  src/main/java/com/example/yaho/config/AmazonConfig.java
  src/main/java/com/example/yaho/config/SecurityConfig.java
  src/main/java/com/example/yaho/converter/MemberConverter.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/domain/enums/FavoriteTeam.java
  src/main/java/com/example/yaho/repository/DiaryRepository.java
  src/main/java/com/example/yaho/repository/MemberRepository.java
  src/main/java/com/example/yaho/service/MemberService/MemberService.java
  src/main/java/com/example/yaho/utils/SecurityUtil.java
  src/main/java/com/example/yaho/web/controller/MemberController.java
  src/main/java/com/example/yaho/web/dto/MemberResponseDTO.java
  src/main/java/com/example/yaho/web/dto/MemberUpdateDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#49 ✨ [Feature] 감정 이모티콘, 구단 로고 불러오기 API
  src/main/java/com/example/yaho/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/yaho/converter/DiaryConverter.java
  src/main/java/com/example/yaho/domain/Diary.java
  src/main/java/com/example/yaho/domain/Game.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/domain/enums/FavoriteClub.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryService.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/com/example/yaho/validation/annotation/CheckEmotion.java
  src/main/java/com/example/yaho/validation/validator/EmotionCheckValidator.java
  src/main/java/com/example/yaho/web/controller/DiaryController.java
  src/main/java/com/example/yaho/web/dto/DiaryRequestDTO.java
  src/main/java/com/example/yaho/web/dto/DiaryResponseDTO.java
Labels: :sparkles: feature

#51 ♻️ [Refactor] application.yml 환경변수 설정
  src/main/resources/application.yml
Labels: :recycle: refactor

#56 ♻️ [Refactor] 오류 해결, mvp image api 구현
  src/main/java/com/example/yaho/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/yaho/aws/s3/AmazonS3Manager.java
  src/main/java/com/example/yaho/converter/DiaryConverter.java
  src/main/java/com/example/yaho/converter/MemberConverter.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryService.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/com/example/yaho/service/MemberService/MemberService.java
  src/main/java/com/example/yaho/web/controller/DiaryController.java
  src/main/java/com/example/yaho/web/dto/DiaryRequestDTO.java
  src/main/java/com/example/yaho/web/dto/DiaryResponseDTO.java
  src/main/java/com/example/yaho/web/dto/MemberResponseDTO.java
  src/main/java/com/example/yaho/web/dto/MemberUpdateDTO.java
Labels: :sparkles: feature, :recycle: refactor

#59 [Refactor] 깃허브 액션 오류 관련 멤버 코드 수정
  src/main/java/com/example/yaho/config/SecurityConfig.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/domain/enums/FavoriteTeam.java
  src/main/java/com/example/yaho/repository/DiaryRepository.java
  src/main/java/com/example/yaho/service/MemberService/MemberService.java
  src/main/java/com/example/yaho/utils/SecurityUtil.java
  src/main/java/com/example/yaho/web/dto/MemberResponseDTO.java
  src/main/java/com/example/yaho/web/dto/MemberUpdateDTO.java
Labels: :recycle: refactor

#68 [Refactor] 이미지 url 변경
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryServiceImpl.java
Labels: :recycle: refactor

#70 [Refactor] 엑세스 토큰 추가
  src/main/java/com/example/yaho/service/KakaoService/KakaoService.java
  src/main/java/com/example/yaho/web/dto/LoginResponseDto.java
Labels: :recycle: refactor

#73 ✨ [Feature/18] 카카오 회원탈퇴 API
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/domain/enums/FairyGrade.java
  src/main/java/com/example/yaho/service/KakaoService/KakaoService.java
  src/main/java/com/example/yaho/web/controller/KakaoLoginController.java
Labels: :sparkles: feature

#77 ♻️ [Refactor] member 객체 수정
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/service/KakaoService/KakaoService.java
  src/main/java/com/example/yaho/web/controller/KakaoLoginController.java
  src/main/java/com/example/yaho/web/controller/KakaoLogoutController.java
Labels: :recycle: refactor

#85 [Fix] WebConfig 파일 수정
  src/main/java/com/example/yaho/config/WebConfig.java
Labels: :bug: bug

#81 ✨ [Feature] 멤버 생성 API
  src/main/java/com/example/yaho/converter/MemberConverter.java
  src/main/java/com/example/yaho/domain/Member.java
  src/main/java/com/example/yaho/repository/MemberRepository.java
  src/main/java/com/example/yaho/service/KakaoService/KakaoService.java
  src/main/java/com/example/yaho/service/MemberService/MemberService.java
  src/main/java/com/example/yaho/web/controller/KakaoLoginController.java
  src/main/java/com/example/yaho/web/controller/MemberController.java
  src/main/java/com/example/yaho/web/dto/LoginResponseDto.java
  src/main/java/com/example/yaho/web/dto/MemberRequestDTO.java
  src/main/java/com/example/yaho/web/dto/MemberResponseDTO.java
Labels: :sparkles: feature

#87 [fix] PATCH 권한 허용
  src/main/java/com/example/yaho/config/WebConfig.java
Labels: :bug: bug

#92 [fix] location 값 추가
  src/main/java/com/example/yaho/converter/DiaryConverter.java
  src/main/java/com/example/yaho/domain/enums/Location.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/com/example/yaho/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/com/example/yaho/web/controller/DiaryController.java
Labels: :bug: bug
